CONFIG_NAME: interop
PRESET_BASE: interop

# Time parameters
SECONDS_PER_SLOT: 12 # 2초 보다 반드시 커야 한다. ( SECONDS_PER_SLOT > 2) 
# [SECONDS_PER_SLOT] AttestationSubnetCount 와도 연관이 있다.
# [SECONDS_PER_SLOT] subnetCount := params.BeaconConfig().AttestationSubnetCount
# [SECONDS_PER_SLOT] subnetWeight := activeValidators / subnetCount
# [SECONDS_PER_SLOT] numPerSlot := time.Duration(subnetWeight / uint64(params.BeaconConfig().SlotsPerEpoch)) != 0
SLOTS_PER_EPOCH: 6
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_VERSION: 0x20000090
ALTAIR_FORK_EPOCH: 0

# Bellatrix
BELLATRIX_FORK_VERSION: 0x20000091
BELLATRIX_FORK_EPOCH: 0
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_VERSION: 0x20000092
CAPELLA_FORK_EPOCH: 0

# Deneb
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x6939693969396939693969396939693969396939